import { describe, expect, it } from "vitest";
import {
  isGeneratedRecord,
  MASTER_DATA_TAG_FIELDS,
  TRANSACTION_ENTITIES
} from "../src/generated-identity.js";

// The one "is this ours?" rule, as a decision table. Every row: entity, record, tag, answer.
const T = "EZTD";

const table = [
  // Master data written by current loads: the tag field decides, whatever the name.
  [
    "Customer",
    { Notes: "EZTD-CUST-001 (generated by EasyTestData)", DisplayName: "Acme" },
    T,
    true
  ],
  ["Vendor", { AcctNum: "EZTD-VEND-003", DisplayName: "Supply Co" }, T, true],
  ["Employee", { EmployeeNumber: "EZTD-EMP-002", DisplayName: "Pat Lee" }, T, true],
  ["Item", { Description: "EZTD", Name: "EZTD-CONSULT" }, T, true],
  ["Customer", { Notes: "eztd-cust-001", DisplayName: "Acme" }, T, true],
  // Another tag, or a tag that only shares a prefix: not ours.
  ["Vendor", { AcctNum: "DEMO-VEND-003", DisplayName: "Supply Co" }, T, false],
  ["Vendor", { AcctNum: "EZTDX-VEND-003", DisplayName: "EZTD-VENDOR-003" }, T, false],
  // A tag field holding the user's own value is the user's, whatever the name.
  ["Vendor", { AcctNum: "12345", DisplayName: "EZTD Payroll Service" }, T, false],
  ["Employee", { EmployeeNumber: "E-7", DisplayName: "EZTD Carol 03" }, T, false],
  // A name alone never makes a record ours, even one shaped like a generated tag.
  ["Vendor", { DisplayName: "EZTD-VENDOR-001" }, T, false],
  ["Vendor", { DisplayName: "eztd-vendor-012" }, T, false],
  ["Vendor", { AcctNum: "", DisplayName: "EZTD Payroll Service" }, T, false],
  ["Employee", { DisplayName: "EZTD Alice 01" }, T, false],
  ["Employee", { EmployeeNumber: "  ", DisplayName: "EZTD Bob 02" }, T, false],
  ["Vendor", { DisplayName: "DEMO+1-VENDOR-001" }, "DEMO+1", false],
  ["Vendor", { DisplayName: "EZTD Supplies" }, T, false],
  ["Vendor", { DisplayName: "EZTD-VENDOR-01" }, T, false],
  ["Vendor", { DisplayName: "EZTD-VENDOR-0001" }, T, false],
  ["Vendor", { DisplayName: "EZTD-VENDOR-001 Inc" }, T, false],
  ["Employee", { DisplayName: "EZTD Alice 001" }, T, false],
  ["Employee", { DisplayName: "EZTD Alice 1" }, T, false],
  ["Employee", { DisplayName: "EZTD Alice" }, T, false],
  ["Vendor", { DisplayName: "EZTD Payroll Services Inc" }, T, false],
  ["Employee", { DisplayName: "EZTD Mary Ann 01" }, T, false],
  ["Employee", { DisplayName: "EZTDX Carol 01" }, T, false],
  ["Vendor", { DisplayName: "Amy's Bird Sanctuary" }, "AMY", false],
  ["Vendor", { DisplayName: "A-1 Plumbing" }, "A", false],
  ["Employee", { DisplayName: "A Smith 1" }, "A", false],
  ["Vendor", { DisplayName: "PG&E" }, "PG", false],
  ["Vendor", { DisplayName: "DEMOX1-VENDOR-001" }, "DEMO.1", false],
  // Customers and items: tag field only, whatever the name.
  ["Customer", { DisplayName: "EZTD-CLIENT-001" }, T, false],
  ["Customer", { DisplayName: "Amy's Bird Sanctuary" }, "AMY", false],
  ["Item", { Name: "EZTD-CONSULT" }, T, false],
  ["Customer", { Notes: "Key account", DisplayName: "EZTD-CLIENT-001" }, T, false],
  // Transactions: PrivateNote or DocNumber.
  ["Invoice", { PrivateNote: "EZTD", DocNumber: "1001" }, T, true],
  ["Bill", { DocNumber: "EZTD-BILL-0004" }, T, true],
  ["JournalEntry", { PrivateNote: "EZTD monthly depreciation" }, T, true],
  ["Invoice", { PrivateNote: "Paid by check", DocNumber: "1001" }, T, false],
  ["Invoice", { CustomerMemo: { value: "EZTD" } }, T, false],
  ["Payment", {}, T, false]
];

describe("isGeneratedRecord", () => {
  it.each(table)("%s %j (tag %s) → %s", (entity, record, tag, expected) => {
    expect(isGeneratedRecord(entity, record, tag)).toBe(expected);
  });

  it("matches nothing without a tag or a record", () => {
    expect(isGeneratedRecord("Vendor", { AcctNum: "EZTD-VEND-1" }, "")).toBe(false);
    expect(isGeneratedRecord("Vendor", { AcctNum: "EZTD-VEND-1" }, null)).toBe(false);
    expect(isGeneratedRecord("Vendor", null, T)).toBe(false);
  });

  it("has a tag field for each master data type", () => {
    expect(Object.keys(MASTER_DATA_TAG_FIELDS).sort()).toEqual([
      "Customer",
      "Employee",
      "Item",
      "Vendor"
    ]);
  });

  it("covers every transaction type purge deletes, and refuses a type it has no rule for", () => {
    expect(TRANSACTION_ENTITIES).toHaveLength(15);
    expect(() => isGeneratedRecord("Account", { Name: "EZTD Checking" }, T)).toThrow(
      /No generated/
    );
  });
});

// Load reuse, Remove test data and ensureServiceItem all decide through isGeneratedRecord: nothing else
// in the package matches tags itself.
describe("one rule", () => {
  it("only generated-identity.js matches tags", async () => {
    const { readdirSync, readFileSync } = await import("node:fs");
    const dir = new URL("../src/", import.meta.url);
    const matching = readdirSync(dir).filter(
      (file) =>
        file !== "generated-identity.js" &&
        /tagMatches\(/.test(readFileSync(new URL(file, dir), "utf8"))
    );
    expect(matching).toEqual([]);
  });
});
