import { describe, expect, it, vi } from "vitest";
import { generate, resolveConfig } from "@easytestdata/core";
import { loadPlanIntoQbo, uniqueDisplayName } from "../src/load-service.js";

/**
 * A QBO stand-in whose Customer/Vendor query returns `existing[entity]` (first page only) and
 * whose batch creates answer with fresh Ids.
 */
function fakeQbo(existing = {}) {
  let nextId = 1000;
  const created = [];
  const client = {
    query: async (sql) => {
      const entity = sql.match(/from (\w+)/)[1];
      const firstPage = /startposition 1 /.test(sql);
      return { QueryResponse: firstPage && existing[entity] ? { [entity]: existing[entity] } : {} };
    },
    update: vi.fn(async (entity, payload) => ({ [entity]: payload })),
    batch: vi.fn(async (request) => ({
      BatchItemResponse: request.map((item) => {
        const [entityKey] = Object.keys(item).filter((k) => !["bId", "operation"].includes(k));
        created.push({ entity: entityKey, payload: item[entityKey] });
        return { bId: item.bId, [entityKey]: { Id: String(nextId++), SyncToken: "0" } };
      })
    }))
  };
  return { client, created };
}

describe("loading parties into a sandbox that already has records", () => {
  const plan = generate({
    template: "saas",
    startDate: "2025-01-01",
    months: 1,
    customerCount: 3,
    seed: 11
  });
  const [first, second] = plan.customers;

  it("reuses only tagged records and gives a clashing party a distinct name", async () => {
    const { client, created } = fakeQbo({
      Customer: [
        // An unrelated customer that happens to share the generated name.
        { Id: "1", SyncToken: "0", DisplayName: first.name, Active: true, Notes: "real client" },
        // A customer an earlier load created (tagged), now inactive.
        {
          Id: "2",
          SyncToken: "3",
          DisplayName: second.name,
          Active: false,
          Notes: `${plan.tag}-${second.id} (generated by EasyTestData)`
        }
      ]
    });

    const result = await loadPlanIntoQbo(client, plan, null, () => {});

    const customers = created.filter((c) => c.entity === "Customer").map((c) => c.payload);
    const names = customers.map((c) => c.DisplayName);
    // The untagged record is not reused: the generated party is created under a new name.
    expect(names).toContain(`${first.name} (${plan.tag})`);
    expect(names).not.toContain(first.name);
    expect(customers.find((c) => c.DisplayName === `${first.name} (${plan.tag})`).Notes).toMatch(
      new RegExp(`^${plan.tag}-`)
    );
    // The tagged record is reactivated and reused, not created again.
    expect(names).not.toContain(second.name);
    expect(client.update).toHaveBeenCalledWith("customer", expect.objectContaining({ Id: "2" }));
    // Nothing was attached to the unrelated customer.
    const invoices = created.filter((c) => c.entity === "Invoice").map((c) => c.payload);
    expect(invoices.length).toBeGreaterThan(0);
    expect(invoices.some((inv) => inv.CustomerRef?.value === "1")).toBe(false);
    expect(result).toBeDefined();
  });
});

/**
 * Like fakeQbo, but it answers queries the way QBO does for name-list entities: inactive records
 * are returned only when the where clause asks for them (`Active IN (true, false)` or
 * `Active = false`). Batch creates of a DisplayName/Name QBO already holds (active or not) fail
 * with a Duplicate Name fault.
 */
function qboWithInactive(existing = {}) {
  let nextId = 2000;
  const created = [];
  const client = {
    query: async (sql) => {
      const entity = sql.match(/from (\w+)/)[1];
      if (!/startposition 1 /.test(sql)) return { QueryResponse: {} };
      const includeInactive = /Active\s+in\s*\(\s*true\s*,\s*false\s*\)/i.test(sql);
      const onlyInactive = /Active\s*=\s*false/i.test(sql);
      const rows = (existing[entity] || []).filter((r) =>
        includeInactive ? true : onlyInactive ? r.Active === false : r.Active !== false
      );
      return { QueryResponse: rows.length ? { [entity]: rows } : {} };
    },
    update: vi.fn(async (entity, payload) => ({ [entity]: payload })),
    batch: vi.fn(async (request) => ({
      BatchItemResponse: request.map((item) => {
        const [entityKey] = Object.keys(item).filter((k) => !["bId", "operation"].includes(k));
        const payload = item[entityKey];
        const name = payload.DisplayName || payload.Name;
        const taken = Object.values(existing)
          .flat()
          .some((r) => name && (r.DisplayName || r.Name) === name);
        if (taken) {
          return { bId: item.bId, Fault: { Error: [{ Message: "Duplicate Name Exists Error" }] } };
        }
        created.push({ entity: entityKey, payload });
        return { bId: item.bId, [entityKey]: { Id: String(nextId++), SyncToken: "0" } };
      })
    }))
  };
  return { client, created };
}

describe("reloading after Remove test data or rollback made generated records inactive", () => {
  const plan = generate({
    template: "saas",
    startDate: "2025-01-01",
    months: 1,
    customerCount: 3,
    seed: 11
  });
  const [first] = plan.customers;
  const [vendor] = plan.vendors;
  const [employee] = plan.employees;

  it("reactivates the inactive tagged customer, vendor, employee and item instead of re-creating them", async () => {
    const config = resolveConfig(plan.meta?.industry || {}, {}, plan.country || "US");
    const itemName = `${plan.tag}-${config.serviceItems[0].suffix}`;
    const { client, created } = qboWithInactive({
      Customer: [
        {
          Id: "21",
          SyncToken: "4",
          DisplayName: first.name,
          Active: false,
          Notes: `${plan.tag}-${first.id} (generated by EasyTestData)`
        }
      ],
      Vendor: [
        {
          Id: "31",
          SyncToken: "1",
          DisplayName: vendor.name,
          Active: false,
          AcctNum: `${plan.tag}-${vendor.id}`
        }
      ],
      Employee: employee
        ? [
            {
              Id: "41",
              SyncToken: "1",
              DisplayName: employee.name,
              Active: false,
              EmployeeNumber: `${plan.tag}-${employee.id}`
            }
          ]
        : [],
      Item: [{ Id: "51", SyncToken: "2", Name: itemName, Description: plan.tag, Active: false }]
    });

    const result = await loadPlanIntoQbo(client, plan, null, () => {});

    const names = created.map((c) => c.payload.DisplayName).filter(Boolean);
    expect(names).not.toContain(first.name);
    expect(names).not.toContain(vendor.name);
    expect(created.map((c) => c.payload.Name)).not.toContain(itemName);
    expect(client.update).toHaveBeenCalledWith("item", expect.objectContaining({ Id: "51" }));
    expect(client.update).toHaveBeenCalledWith("customer", expect.objectContaining({ Id: "21" }));
    expect(client.update).toHaveBeenCalledWith("vendor", expect.objectContaining({ Id: "31" }));
    if (employee) {
      expect(names).not.toContain(employee.name);
      expect(client.update).toHaveBeenCalledWith("employee", expect.objectContaining({ Id: "41" }));
    }
    expect(result.counts.customersReactivated).toBe(1);
    expect(result.failures).toEqual([]);
  });

  it("gives a party a distinct name when an inactive untagged record holds its name", async () => {
    const { client, created } = qboWithInactive({
      Customer: [
        { Id: "22", SyncToken: "0", DisplayName: first.name, Active: false, Notes: "old client" }
      ]
    });

    const result = await loadPlanIntoQbo(client, plan, null, () => {});

    const names = created.filter((c) => c.entity === "Customer").map((c) => c.payload.DisplayName);
    expect(names).toContain(`${first.name} (${plan.tag})`);
    expect(client.update).not.toHaveBeenCalledWith(
      "customer",
      expect.objectContaining({ Id: "22" })
    );
    expect(result.failures).toEqual([]);
  });
});

describe('a generated record an earlier load had to create as "Name (TAG)"', () => {
  const plan = generate({
    template: "saas",
    startDate: "2025-01-01",
    months: 1,
    customerCount: 3,
    seed: 11
  });
  const [first] = plan.customers;
  const [vendor] = plan.vendors;
  const config = resolveConfig(plan.meta?.industry || {}, {}, plan.country || "US");
  const itemName = `${plan.tag}-${config.serviceItems[0].suffix}`;

  it("is found and reused (or reactivated) by the next load, not created again", async () => {
    const { client, created } = qboWithInactive({
      Customer: [
        { Id: "61", SyncToken: "0", DisplayName: first.name, Active: true, Notes: "real client" },
        {
          Id: "62",
          SyncToken: "0",
          DisplayName: `${first.name} (${plan.tag})`,
          Active: true,
          Notes: `${plan.tag}-${first.id} (generated by EasyTestData)`
        }
      ],
      Vendor: [
        { Id: "71", SyncToken: "0", DisplayName: vendor.name, Active: true, AcctNum: "V-9" },
        {
          Id: "72",
          SyncToken: "1",
          DisplayName: `${vendor.name} (${plan.tag})`,
          Active: false,
          AcctNum: `${plan.tag}-${vendor.id}`
        }
      ],
      Item: [
        { Id: "81", SyncToken: "0", Name: itemName, Description: "Our own", Active: true },
        {
          Id: "82",
          SyncToken: "3",
          Name: `${itemName} (${plan.tag})`,
          Description: plan.tag,
          Active: false
        }
      ]
    });

    const result = await loadPlanIntoQbo(client, plan, null, () => {});

    const displayNames = created.map((c) => c.payload.DisplayName).filter(Boolean);
    expect(displayNames.filter((n) => n.startsWith(first.name))).toEqual([]);
    expect(displayNames.filter((n) => n.startsWith(vendor.name))).toEqual([]);
    const itemNames = created.map((c) => c.payload.Name).filter(Boolean);
    expect(itemNames.filter((n) => n.startsWith(itemName))).toEqual([]);
    // The inactive tagged vendor and item are reactivated; the user's records are untouched.
    expect(client.update).toHaveBeenCalledWith("vendor", expect.objectContaining({ Id: "72" }));
    expect(client.update).toHaveBeenCalledWith("item", expect.objectContaining({ Id: "82" }));
    for (const id of ["61", "71", "81"]) {
      expect(client.update).not.toHaveBeenCalledWith(
        expect.anything(),
        expect.objectContaining({ Id: id })
      );
    }
    // Transactions attach to the tagged customer, never to the user's.
    const invoices = created.filter((c) => c.entity === "Invoice").map((c) => c.payload);
    expect(invoices.some((inv) => inv.CustomerRef?.value === "62")).toBe(true);
    expect(invoices.some((inv) => inv.CustomerRef?.value === "61")).toBe(false);
    expect(result.failures).toEqual([]);
  });
});

describe("a service item name held by an item this tool did not create", () => {
  const plan = generate({
    template: "saas",
    startDate: "2025-01-01",
    months: 1,
    customerCount: 3,
    seed: 11
  });
  const config = resolveConfig(plan.meta?.industry || {}, {}, plan.country || "US");
  const itemName = `${plan.tag}-${config.serviceItems[0].suffix}`;

  it("is left alone (never reactivated); the generated item gets a tagged distinct name", async () => {
    const { client, created } = qboWithInactive({
      Item: [{ Id: "91", SyncToken: "0", Name: itemName, Description: "Mine", Active: false }]
    });

    const result = await loadPlanIntoQbo(client, plan, null, () => {});

    expect(client.update).not.toHaveBeenCalledWith("item", expect.objectContaining({ Id: "91" }));
    const item = created.find((c) => c.entity === "Item" && c.payload.Name.startsWith(itemName));
    expect(item.payload).toMatchObject({
      Name: `${itemName} (${plan.tag})`,
      Description: plan.tag
    });
    const lines = created
      .filter((c) => c.entity === "Invoice")
      .flatMap((c) => c.payload.Line || []);
    expect(lines.some((l) => l.SalesItemLineDetail?.ItemRef?.value === "91")).toBe(false);
    expect(result.failures).toEqual([]);
  });
});

describe("a customer, vendor or employee QBO refuses to create", () => {
  it("is listed in the load's failures with QBO's reason", async () => {
    const plan = generate({
      template: "saas",
      startDate: "2025-01-01",
      months: 1,
      customerCount: 3,
      seed: 11
    });
    const [first] = plan.customers;
    const { client } = fakeQbo();
    const batch = client.batch;
    client.batch = vi.fn(async (request) => {
      const response = await batch(request);
      response.BatchItemResponse = response.BatchItemResponse.map((resp, i) =>
        request[i].Customer?.DisplayName === first.name
          ? { bId: resp.bId, Fault: { Error: [{ Message: "Duplicate Name Exists Error" }] } }
          : resp
      );
      return response;
    });

    const result = await loadPlanIntoQbo(client, plan, null, () => {});

    expect(result.failures).toContainEqual(
      expect.objectContaining({
        entity: "Customer",
        ref: first.name,
        message: "Duplicate Name Exists Error"
      })
    );
  });
});

describe("uniqueDisplayName", () => {
  it("keeps a free name, suffixes a taken one, and counts up past further clashes", () => {
    const taken = new Set(["ACME LTD", "ACME LTD (EZTD)"]);
    expect(uniqueDisplayName("Blue Co", "EZTD", taken)).toBe("Blue Co");
    expect(uniqueDisplayName("Acme Ltd", "EZTD", taken)).toBe("Acme Ltd (EZTD 2)");
    // Chosen names are reserved for the rest of the load.
    expect(uniqueDisplayName("Blue Co", "EZTD", taken)).toBe("Blue Co (EZTD)");
  });

  it("stays within QBO's 100-character limit", () => {
    const long = "x".repeat(100);
    const name = uniqueDisplayName(long, "EZTD", new Set([long.toUpperCase()]));
    expect(name).toHaveLength(100);
    expect(name.endsWith(" (EZTD)")).toBe(true);
  });
});
